stages:
  - check:static

# default rules for jobs execution
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

dart-formatter:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script: fvm flutter format --dry-run --set-exit-if-changed .
