stages:
  - check:static

# default rules for jobs execution
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

dart-formatter:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script: fvm flutter format --dry-run --set-exit-if-changed .

dart-analyzer:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script: fvm flutter analyze --fatal-infos --fatal-warnings

code-generation-mismatch-check:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script:
    - fvm flutter pub get
    - fvm flutter pub run build_runner build --delete-conflicting-outputs --fail-on-severe
    - (( $(git status --untracked-files=no --porcelain|wc -l) == 0 )) || { echo >&2 "Some changes in generated files detected"; exit 1; }
