stages:
  - check:static
  - check:tests
  - build:prepare
  - release

# default rules for jobs execution
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

dart-formatter:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script: fvm flutter format --dry-run --set-exit-if-changed .

dart-analyzer:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script: fvm flutter analyze --fatal-infos --fatal-warnings

code-generation-mismatch-check:
  image: volkovpishet/flutter-base:1
  stage: check:static
  interruptible: true
  script:
    - fvm flutter pub get
    - fvm flutter pub run build_runner build --delete-conflicting-outputs --fail-on-severe
    - (( $(git status --untracked-files=no --porcelain|wc -l) == 0 )) || { echo >&2 "Some changes in generated files detected"; exit 1; }

generate-skia-shaders-cache:
  image: volkovpishet/flutter-android:1
  stage: build:prepare
  when: manual
  cache:
    policy: push
    paths:
      - flutter_shaders_warm_up_data.sksl.json
  script:
    - run-emulator
    - fvm flutter drive --profile --cache-sksl --purge-persistent-cache --write-sksl-on-exit flutter_shaders_warm_up_data.sksl.json --driver=test_driver/integration_test.dart --target=test/shaders_warm_up_test.dart

tests:
  image: volkovpishet/flutter-base:1
  stage: check:tests
  script:
    - fvm flutter test

release:android:
  image: volkovpishet/flutter-android:1
  cache:
    policy: pull
    paths:
      - flutter_shaders_warm_up_data.sksl.json
  before_script:
    - echo ${ANDROID_SERVICE_ACCOUNT_API_KEY} > android/pc-api-8001975366575556685-777-dd7767eaa5b6.json
    - echo -e ${ANDROID_KEY_PROPERTIES} > android/key.properties
    - echo -n ${ANDROID_SIGNING_JKS_AS_BASE64_STRING} | base64 -d > android/app/upload-keystore.jks
  stage: release
  when: manual
  script:
    - fvm flutter pub get
    - fvm flutter build appbundle --bundle-sksl-path flutter_shaders_warm_up_data.sksl.json
    - cd android
    - bundle install
    - bundle exec fastlane release
