default_platform(:ios)

platform :ios do
  desc "Release Flutter app"
  lane :release do
    keychain_name = "mobx-counter-app-fastlane.keychain"
    keychain_pass = SecureRandom.base64

    # wipe old keychain data
    begin
        delete_keychain(name: keychain_name)
    rescue => ex
        UI.message("Keychain could not be deleted: #{ex}")
    end

    # create new temporary keychain
    create_keychain(
      name: keychain_name,
      password: keychain_pass,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )

    # fetch and add to keychain provisioning profiles and certificates
    match(
      type: "appstore",
      keychain_name: keychain_name,
      keychain_password: keychain_pass,
    )

    build_app(scheme: "Runner")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: "fastlane/fastlane-api-key.json",
    )
  end
end
